version: '3.7'
services:
  server:
    container_name: auth
    build:
      dockerfile: Dockerfile
    ports:
      - "8121:8121"
    restart: always
    environment:
      PORT: 8121
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_PORT: 27017