version: '3.7'
services:
## mongo db service 
  mongo-db:
    container_name: auth_mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"