// Code generated by mockery v2.20.0. DO NOT EDIT.

package repositories

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Jamify-app/auth/processes/identities/models"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

// CreateIdentity provides a mock function with given fields: _a0, _a1
func (_m *MockIRepository) CreateIdentity(_a0 *gin.Context, _a1 *models.Identity) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *models.Identity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetIdentity provides a mock function with given fields: _a0, _a1
func (_m *MockIRepository) GetIdentity(_a0 *gin.Context, _a1 string) (*models.Identity, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, string) (*models.Identity, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, string) *models.Identity); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockIRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIRepository(t mockConstructorTestingTNewMockIRepository) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
